name: Release to Maven Central

on:
  workflow_dispatch:   # manual trigger
  push:
    tags:
      - 'v*'           # release when a tag like v0.0.1 is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: maven
          server-id: central
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Prepare Maven environment with Java 17 for deployment to Sonatype
        run: export JAVA_TOOL_OPTIONS="--add-exports=java.base/sun.nio.ch=ALL-UNNAMED"

      - name: Build & Deploy
        run: mvn clean deploy -P release -B -U -DskipTests
        env:
          SONATYPE_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.CENTRAL_TOKEN }}
          GPG_TTY: $(tty)
